### PR TITLE
Chore: improve Dockerfile, make the docker image can be use in Raspberry Pi

### PR DESCRIPTION
**Pull request by bolasblack**
So we can use the docker image in Raspberry Pi or other arch like

    docker run --name clash dreamacro/clash /clash-linux-armv7

### CODE REVIEW

**Comment by Dreamacro** [comment]
It makes images large. I push `Dockerfile.arm32v7` and `Dockerfile.arm64v8`, but It doesn't build automated now.

**Comment by bolasblack** [comment]
@Dreamacro Great!

Maybe you can trigger build manually like this?

图片

图片

**Comment by Dreamacro** [comment]
@bolasblack Yes, I have tried to use docker hub automated build, but it built failed.

image

It seems that missing `qemu-user-static` (https://stackoverflow.com/questions/54578066/how-to-build-a-docker-image-on-a-specific-architecture-with-docker-hub). I would do it later.

**Comment by bolasblack** [comment]
Thank you so much!

**Comment by Dreamacro** [comment]
close because have another solution

**Pull request closed without merging**
