### PR TITLE
Fix: HTTP Status Code `100 Continue` support"

### PR DESCRIPTION
**Pull request by soarqin**
https://tools.ietf.org/html/rfc7231#section-6.2.1

This is just a temporary fix for it:
1. remove `Expect: 100-continue` from request header
2. if got `100 Continue` by accident, just read another request

To fix it completely, we must(but no need unless you care about the wait time of 100-contine):
1. read only headers and check `Expect: 100-continue`, if not found, just continue to read body and send the whole request and skip all steps followed
2. send headers without data body
3. read response with status code `100 Continue`, if timeout or got incorrect status code, close the connection with certain status code returned (skip step 4)
4. read data body, send it and read response

### CODE REVIEW

**Comment by Dreamacro** [comment]
Is there any real-world application use `100 Continue` for request?

**Comment by soarqin** [comment]
In Mono/.NET Program, System.Net.Http.WebClient sends `Expect: 100-continue` on POST, event with small data.
That's why I got stuck and tried to resolve the problem by http packets capture and analyze.

**Comment by Dreamacro** [comment]
I adjust the style of code, Is this fit your expectation?

**Comment by soarqin** [comment]
yeah, good job.

**Pull request merged**
