### PR TITLE
fix docker label

### PR DESCRIPTION
**Pull request by junjieyuan**
Signed-off-by: Junjie Yuan <yuan@junjie.pro>

### CODE REVIEW

**Comment by junjieyuan** [comment]
See [docker docs](https://docs.docker.com/engine/reference/builder/#label).

**Comment by Dreamacro** [comment]
`LABEL a=foo` and `LABEL a foo` should be equivalent, how to prove it:

```
$ docker pull dreamacro/clash
$ docker inspect dreamacro/clash
```

**Comment by junjieyuan** [comment]
Yes, they are equal. But the docker docs did not state that this is the correct way to use it, and GoLand marked it as an error. Should we modify it?

GoLand screenshot

**Comment by Dreamacro** [comment]
Okay, Standardize it.

**Comment by Dreamacro** [comment]
Thanks

**Pull request merged**
