### PR TITLE
Feature: add command-line options to override `external-controller`, `secret` and `external-ui` (#531)

### PR DESCRIPTION
**Pull request by ysc3839**
Discussion: #531

### CODE REVIEW

**Comment by Dreamacro** [comment]
implementation an Option for config like https://github.com/Dreamacro/clash/blob/c0a2473160f9da2ea2116358fed33a3e6a77ae5a/common/cache/lrucache.go#L12 maybe more elegant

**Comment by Dreamacro** [comment]
@ysc3839 is there any progress?

**Comment by Dreamacro** [comment]
close because of long time no response

**Comment by ysc3839** [comment]
Sorry, I will take a look of this soon.

**Comment by ysc3839** [comment]
Updated, should I create a new pr?

**Comment by Dreamacro** [comment]
@ysc3839 you can edit the branch and reopen this pr

**Comment by ysc3839** [comment]
@Dreamacro There's no "reopen" button. And I already force pushed to provide branch.

**Comment by Dreamacro** [comment]
if `edit` button can't solve the problem, you can open a new pr

**Comment by ysc3839** [comment]
Which `edit` button? I guess only you can reopen this pr.

**Comment by Dreamacro** [comment]
To the right of the title. I can't reopen it either 😷

**Comment by ysc3839** [comment]
It can only edit the title. I will open a new one.

**Pull request closed without merging**
