### PR TITLE
Feature: add loong64 build

### PR DESCRIPTION
**Pull request by znley**

### CODE REVIEW

**Comment by Dreamacro** [comment]
Are you using a loong64 arch cpu?

**Comment by znley** [comment]
> Are you using a loong64 arch cpu?

Yes, I am working on loongarch64 platform. loong64 is short for loongarch64. If you are interested, you can try it  [here](https://cfarm.tetaneutral.net/machines/list/).

Linux kernel and golang already supports loongarch64 now.

**Comment by Dreamacro** [comment]
> golang already supports loongarch64 now

I know, I just don't want to add a platform to support it, but no one uses it. 

Just to be sure, are you using clash on linux with loongarch64 cpu, and not just adding support for it to various projects because you work for it?

**Comment by znley** [comment]
> > golang already supports loongarch64 now
> 
> I know, I just don't want to add a platform to support it, but no one uses it.
> 
> Just to be sure, are you using clash on linux with loongarch64 cpu, and not just adding support for it to various projects because you work for it?

Oh, Yes. I like this project very much. In fact I use clash both at work and personally. I wrote install and use scripts for this stored in my personal account. https://github.com/merore/merore/tree/main/clash

**Comment by znley** [comment]
If you release the loongarch64 binary, It will help me to improve my scripts to support multi-arch installion.

**Comment by Dreamacro** [comment]
thanks

**Comment by songzongquan** [comment]
I support releasing loong64 installation packages. I am also using loong64.

**Pull request merged**
