### PR TITLE
Feature: resolve ip with a proxy adapter (#1264)

### PR DESCRIPTION
**Pull request by yaling888**
Attach the proxy adapter name as a part #fragment of DNS URL
```yaml
dns:
  nameserver:
    - https://1.1.1.1/dns-query#ProxyAdapterName
  fallback:
    - tls://8.8.8.8:853#ProxyAdapterName
```

### CODE REVIEW

**Comment by fakeboboliu** [comment]
For config like:
```
dns:
  nameserver:
    - https://1.1.1.1/dns-query#ProxyAdapterName
  fallback:
    - tls://8.8.8.8:853#ProxyAdapterName
proxies:
  - name: ProxyAdapterName
    server: nbmd.test.lol
```

It will perform like:
 - I want to resolve something
 - DNS request through ProxyAdapterName
 - request to nbmd.test.lol need DNS through ProxyAdapterName
 - request through ProxyAdapterName need to request the IP of nbmd.test.lol need DNS through ProxyAdapterName
 - request through ProxyAdapterName need to request the IP of nbmd.test.lol need DNS through ProxyAdapterName need to request the IP of nbmd.test.lol need DNS through ProxyAdapterName

until timed out

**Comment by yaling888** [comment]
> For config:
> 
> ```yaml
> dns:
>   nameserver:
>     - https://1.1.1.1/dns-query#ProxyAdapterName
>   fallback:
>     - tls://8.8.8.8:853#ProxyAdapterName
> proxies:
>   - name: ProxyAdapterName
>     server: nbmd.test.lol
> ```
> 
> It will perform like:
> 
> * I want to resolve something
> * DNS request through ProxyAdapterName
> * request to nbmd.test.lol need DNS through ProxyAdapterName
> * request through ProxyAdapterName need to request the IP of nbmd.test.lol need DNS through ProxyAdapterName
> * request through ProxyAdapterName need to request the IP of nbmd.test.lol need DNS through ProxyAdapterName need to request the IP of nbmd.test.lol need DNS through ProxyAdapterName
> 
> until timed out
> 

Are you kidding me???
Add at least one non-proxy DNS URL to `nameserver` or add the IP of nbmd.test.lol to `hosts`.

```yaml
dns:
  nameserver:
    - https://doh.pub/dns-query
    - https://1.1.1.1/dns-query#ProxyAdapterName

hosts:
  nbmd.test.lol: x.x.x.x
```

**Comment by fakeboboliu** [comment]
> > For config:
> > ```yaml
> > dns:
> >   nameserver:
> >     - https://1.1.1.1/dns-query#ProxyAdapterName
> >   fallback:
> >     - tls://8.8.8.8:853#ProxyAdapterName
> > proxies:
> >   - name: ProxyAdapterName
> >     server: nbmd.test.lol
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It will perform like:
> > 
> > * I want to resolve something
> > * DNS request through ProxyAdapterName
> > * request to nbmd.test.lol need DNS through ProxyAdapterName
> > * request through ProxyAdapterName need to request the IP of nbmd.test.lol need DNS through ProxyAdapterName
> > * request through ProxyAdapterName need to request the IP of nbmd.test.lol need DNS through ProxyAdapterName need to request the IP of nbmd.test.lol need DNS through ProxyAdapterName
> > 
> > until timed out
> 
> Are you kidding me??? Add at least one non-proxy DNS URL to `nameserver` or add the IP of nbmd.test.lol to `hosts`.
> 
> ```yaml
> dns:
>   nameserver:
>     - https://doh.pub/dns-query
>     - https://1.1.1.1/dns-query#ProxyAdapterName
> 
> hosts:
>   nbmd.test.lol: x.x.x.x
> ```

Yeah, you are right, but did you try to prevent this case in code and example?

That configuration I wrote is just what a user who has seen your documentation will do.

There's no instruction and friendly information about it, and no fallback in code.

You should not send "Are you kidding me???" to me, it's the user should send "Are you kidding me???" to you.

**Comment by lhbdhr** [comment]
https://lancellc.gitbook.io/clash/clash-config-file/dns

use ``nameserver-policy`` can fix your problem too.

**Pull request closed without merging**
