### PR TITLE
Fix: custom hosts should be added to mapping table during the DNS query

### PR DESCRIPTION
**Pull request by yaling888**
Custom hosts should be added to mapping table during the DNS query, that can be restored it when pre handle metadata.

### CODE REVIEW

**Comment by Dreamacro** [comment]
Please describe what problems have been met.

**Comment by yaling888** [comment]
config:
```yaml
hosts:
  'example.com': 'x.x.x.x'

dns:
  enable: true
  use-hosts: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host # or fake-ip

rules:
  - DOMAIN,example.com,proxy
```
problem is that host name 'example.com' cannot match rule DOMAIN.

**Comment by Dreamacro** [comment]
This causes a problem similar to redir-host, where a single ip (e.g. 127.0.0.1) will mapping wrong host if it corresponds to multiple host domains

**Comment by yaling888** [comment]
> This causes a problem similar to redir-host, where a single ip (e.g. 127.0.0.1) will mapping wrong host if it corresponds to multiple host domains

Reducing TTL may alleviate in your case

**Pull request closed without merging**
