### PR TITLE
docs(locales): add chinese locale support

### PR DESCRIPTION
**Pull request by a76yyyy**
Demo: https://a76yyyy.github.io/clash/zh_CN/

### CODE REVIEW

**Comment by a76yyyy** [comment]
I would like to ask, is it time for a review?
@Dreamacro @BirkhoffLee

**Comment by BirkhoffLee** [comment]
> I would like to ask, is it time for a review? @Dreamacro @BirkhoffLee

My review is on above, check it out

**Comment by a76yyyy** [comment]
Are there any problems I need to resolve at this time?

@BirkhoffLee @Dreamacro

**Review by BirkhoffLee — CHANGES_REQUESTED** [review]

**Review by BirkhoffLee — APPROVED** [review]

**Comment by a76yyyy** [comment]
请问是否需要我 resolve 这个 conflicting file?

**Comment by Dreamacro** [comment]
> 请问是否需要我 resolve 这个 conflicting file? 

是的

**Comment by a76yyyy** [comment]
> > 请问是否需要我 resolve 这个 conflicting file?
> 
> 是的

resolved

**Comment by Dreamacro** [comment]
Thanks for your contribution. 🙌

**Pull request merged**
