### PR TITLE
 Feature: DNS fallback-ip configuration

### PR DESCRIPTION
**Pull request by songchenwen**
This allows us to tell clash to give up poisoned DNS results like 243.185.187.39

### CODE REVIEW

**Comment by comzyh** [comment]
Luckily, `gist.github.com` is poison to `243.185.187.39` at my upstream DNS server again. So I have a chance to test this PR, and it works good. Thanks.

Before

```
➜  ~ dig gist.github.com @127.0.0.1 -p 5353
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 23741
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 8; ADDITIONAL: 12

;; QUESTION SECTION:
;; gist.github.com.            IN    A

;; ANSWER SECTION:
gist.github.com.        13808    IN    A    243.185.187.39

;; AUTHORITY SECTION:
github.com.             15485    IN    NS    ns-520.awsdns-01.net.
github.com.             15485    IN    NS    ns3.p16.dynect.net.
github.com.             15485    IN    NS    ns-421.awsdns-52.com.
github.com.             15485    IN    NS    ns4.p16.dynect.net.
github.com.             15485    IN    NS    ns2.p16.dynect.net.
github.com.             15485    IN    NS    ns1.p16.dynect.net.
github.com.             15485    IN    NS    ns-1283.awsdns-32.org.
github.com.             15485    IN    NS    ns-1707.awsdns-21.co.uk.

;; ADDITIONAL SECTION:
ns1.p16.dynect.net.     70783    IN    A    208.78.70.16
ns2.p16.dynect.net.     70544    IN    A    204.13.250.16
ns3.p16.dynect.net.     71124    IN    A    208.78.71.16
ns4.p16.dynect.net.     70544    IN    A    204.13.251.16
ns-421.awsdns-52.com.    99604    IN    A    205.251.193.165
ns-520.awsdns-01.net.    7783    IN    A    205.251.194.8
ns-1283.awsdns-32.org.    89677    IN    A    205.251.197.3
ns-1707.awsdns-21.co.uk.    10953    IN    A    205.251.198.171
ns-421.awsdns-52.com.    99604    IN    AAAA    2600:9000:5301:a500::1
ns-520.awsdns-01.net.    7783    IN    AAAA    2600:9000:5302:800::1
ns-1283.awsdns-32.org.    91470    IN    AAAA    2600:9000:5305:300::1
ns-1707.awsdns-21.co.uk.    12833    IN    AAAA    2600:9000:5306:ab00::1

;; Received 892 B
;; Time 2019-01-22 20:16:58 CST
;; From 127.0.0.1@5353(UDP) in 0.4 ms
```
After 

```
➜  ~ dig gist.github.com @127.0.0.1 -p 5353
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 652
;; Flags: qr rd ra; QUERY: 1; ANSWER: 2; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; gist.github.com.            IN    A

;; ANSWER SECTION:
gist.github.com.        30    IN    A    192.30.253.118
gist.github.com.        30    IN    A    192.30.253.119

;; Received 95 B
;; Time 2019-01-22 20:17:41 CST
;; From 127.0.0.1@5353(UDP) in 108.4 ms
```

**Comment by comzyh** [comment]
This PR has conflicts with dev branch now, can you rebase your branch to the `Dreamacro:dev` branch ?

**Comment by songchenwen** [comment]
> This PR has conflicts with dev branch now, can you rebase your branch to the `Dreamacro:dev` branch ?

Rebased.

**Comment by BirkhoffLee** [comment]
Any further progress on this PR?

**Comment by Dreamacro** [comment]
@songchenwen merge and refactor about the fallback filter, cc

**Comment by songchenwen** [comment]
> @songchenwen merge the latest dev and refactor about the fallback filter, cc

Ah, Finally. Is this PR getting merged?

**Comment by Dreamacro** [comment]
@songchenwen not yet, writing your final check

**Comment by suntong** [comment]
> not yet, waiting your final check

Can we have a new release please, after all been merged, since it fixes the important issue of #95 & #297? thx

**Comment by Dreamacro** [comment]
@suntong there are some problem have to solve, you can compile by your self, or you can use `dreamacro/clash:dev` with docker.

**Comment by songchenwen** [comment]
> > not yet, waiting your final check
> 
> @songchenwen, all good?
> 
> Also, can we have a new release please, after all been merged, since it fixes the important issue of #95 & #297? thx

LGTM

**Pull request merged**
