### PR TITLE
Feature: support basic authentication for DoH

### PR DESCRIPTION
**Pull request by damnever**

### CODE REVIEW

**Comment by Dreamacro** [comment]
Some detailed explanation of pr is needed, such as where the DoH requires basic auth

**Comment by damnever** [comment]
@Dreamacro There are some DoH servers doesn't want to share themself.

> The DoH protocol design allows applications to fully leverage the HTTP ecosystem, including features that are not enumerated [here](https://www.rfc-editor.org/rfc/rfc8484).

**Comment by Dreamacro** [comment]
I'm more interested in knowing which real-world DoH needs Basic Auth

**Comment by damnever** [comment]
I am hosting such a DoH server to do some traffic management which meets my need, and I believe there are many private DoH servers as well.

So What do you think?

**Comment by Dreamacro** [comment]
I don't have any other opinions. I just want to know the scene that everyone uses.

Have you verified that it works?

**Comment by damnever** [comment]
yes, `https://user:pass@dohserver` works for me

**Comment by Dreamacro** [comment]
cool, thanks

**Pull request merged**
