### PR TITLE
Add IPv6 support for FreeBSD.

### PR DESCRIPTION
**Pull request by yonas**
Upstream patch from FreeBSD ports which adds IPv6 support.

### CODE REVIEW

**Comment by Dreamacro** [comment]
@yonas Are you referring to #2473? But that's Linux, it doesn't necessarily work properly under FreeBSD

**Comment by yonas** [comment]
@Dreamacro I've tested it just now and it works on FreeBSD 13.2.

**Comment by Dreamacro** [comment]
Thanks for the contribution, do you mind if I commit this cherry-pick to premium?

**Comment by yonas** [comment]
@Dreamacro I don't mind if you add it to premium. Thanks for committing.

**Pull request merged**
