### PR TITLE
Add full support for SSR

### PR DESCRIPTION
**Pull request by Anankke**
ref https://github.com/Dreamacro/go-shadowsocks2/pull/4

### CODE REVIEW

**Comment by Dreamacro** [comment]
Why not convert `none` to `dummy`?

**Comment by Anankke** [comment]
There is no such thing called `dummy` in SSR protocol; converting this breaks SSR protocol compatibility.

**Comment by Dreamacro** [comment]
```go
if cipher == "none" {
   cipher = "dummy" 
}
```

**Comment by Anankke** [comment]
Both work, which do you prefer?

**Comment by Dreamacro** [comment]
I prefer not to change go-shadowsocks2

**Comment by Anankke** [comment]
Are we good now?

**Comment by Dreamacro** [comment]
Thanks for contributing, and for your patience

**Comment by Anankke** [comment]
NP ala its fixed thank you

**Pull request merged**
