### PR TITLE
Chore: allow tunnels don't set special proxy

### PR DESCRIPTION
**Pull request by wwqgtxx**

### CODE REVIEW

**Comment by Dreamacro** [comment]
It looks like it's throwing the tunnel request back to the rule match, which doesn't seem like good behavior. Are there any usage scenarios?

**Comment by wwqgtxx** [comment]
Maybe some users just want to forward the port of a remote server to the local, and don't want to specify a specific proxy or proxy group.

**Comment by Dreamacro** [comment]
But most of the rules are for the destination address (Host), and there seems to be unnecessary in throwing the request back into the rules to match

**Comment by wwqgtxx** [comment]
Many users are using rule-providers or distribution rules provided by third parties such as airports/subscription conversions. They may want to simply configure tunnels to forward ports and automatically apply the previous rules.

**Pull request closed without merging**
