### PR TITLE
Feature: Add tcp zero copy support

### PR DESCRIPTION
**Pull request by Kr328**
为 直连 TCP 连接增加 零复制 支持
目前仅测试能在 Linux 上正常工作
~~但是同时使 代理的连接 复制 失去了 使用 BufPool 的能力~~ (整好了

TODO:
 - [x] 使代理连接使用 BufPool

### CODE REVIEW

**Comment by Kr328** [comment]
https://github.com/Dreamacro/clash/issues/622

**Comment by mayanez** [comment]
Hi,
Sorry to necro-comment. 

I was just curious, any reason why this was not merged? I was looking into this to get better performance.

**Comment by Dreamacro** [comment]
@mayanez Its implementation is based on exposing a `Conn() net.Conn` method, which is not elegant enough. I'm going to try something later and see if I can implement this elegantly.

**Comment by fishg** [comment]
这个还有计划实现吗

**Comment by EkkoG** [comment]
Any update?

**Pull request closed without merging**
