### PR TITLE
docs: place logo in public directory

### PR DESCRIPTION
**Pull request by BirkhoffLee**
In development, `/logo.png` is automatically served as-is at `/`, while in production it is discarded and we should've placed at `/public/logo.png` (https://vitepress.dev/guide/asset-handling#the-public-directory)

### CODE REVIEW

**Comment by BirkhoffLee** [comment]
works at https://birkhofflee.github.io/clash/

**Comment by Dreamacro** [comment]
docs/logo.png used on other projects, maybe just cp into the dist directory?

**Comment by BirkhoffLee** [comment]
maybe we can do a soft link from docs/public/logo.png to docs/logo.pngSent from my iPhoneOn 18 May 2023, at 22:11, Dreamacro ***@***.***> wrote:﻿
docs/logo.png used on other projects, maybe just cp into the dist directory?

**Comment by Dreamacro** [comment]
soft link sounds good

**Pull request merged**
